### ISSUE TITLE
Sift::Client.track returns nil on error which makes logging errors to common bug tracking solutions difficult

### ISSUE THREAD

**Issue by rbone** [SiftScience/sift-ruby#29]
Currently when a call is made to `Sift::Client.track` there are two possible responses, either a `Sift::Response` object is returned, or it returns `nil` if an error occurs and logs to the `Sift.logger` the details. Unfortunately this makes it rather hard to track these sorts of errors in tools like [Sentry](https://getsentry.com) or [Bugsnag](https://bugsnag.com). The best we're able to do is simply log our own error indicating that something went wrong, and then immediately check the logs to see what the actual error was.

I'd like to submit a PR to change this behaviour, but before I do I wanted to check what the preferences were for how that change should look. There are a couple of questions I have:
1. Should calling `track` simply let exceptions bubble up rather than catching them, or should it always return a response object and simply provide error details in the response object. My preference is for the former as it gives more options in how to handle that error.
2. How important is backwards compatibility? If you're not worried about breaking compatibility and you're happy to tag a 2.0 release then that's great. However if you are concerned about not wanting to break compatibility just yet I could either create entirely new methods that behave differently (e.g. add a `track_event` method that lets the exceptions bubble up), or I could add a configuration option that lets people toggle this behaviour on/off (defaulting to off to preserve backwards compatibility).

If you're able to provide feedback on this and what approach (if any) you think is best I'm more than happy to put together a PR.

Cheers.

**Comment by zsolthanko** [comment]
It's not clear to me which exception would bubble up

**Comment by rbone** [comment]
@zsolthanko The most likely case is exceptions raised by `HTTParty` due to a connection failure or similar error.

**Comment by MauricioMurga** [comment]
:+1:

**Comment by fredsadaghiani** [comment]
@rbone how about adding a `track!` method that potentially raises an exception?

**Comment by rbone** [comment]
Hey @fredsadaghiani, adding a `track!` method sounds like a good solution to me. I'm a bit busy just at the moment but I'll see if I can get a PR ready sometime next week. Thanks for the feedback!
