### ISSUE TITLE
`track` method returns `nil`

### ISSUE THREAD

**Issue by mz026** [SiftScience/sift-ruby#47]
`Sift::Client#track` method returns `nil` occasionally, I think it is returned by [this line](https://github.com/SiftScience/sift-ruby/blob/master/lib/sift/client.rb#L235)

May I know under which case will the http call raise `StandardError`?

**Comment by KaoruDev** [comment]
You may look at your logs to find the backtrace. Apologies for not making it easier to debug, I've added a feature to have the request return an object with details about the error instead of just logging it. See #39 for more details.
