### ISSUE TITLE
apply_desision_to, undefined method?

### ISSUE THREAD

**Issue by haydencarlson** [SiftScience/sift-ruby#48]
`NoMethodError Exception: undefined method `apply_decision_to' for #<Sift::Client:0x007f17bdb24d38>`

I tried apply_decision and it works. I would have thought someone else would have caught this by now?
Is there something i'm missing here or should I make a pr?

**Comment by KaoruDev** [comment]
Ah sorry for the confusion @haydencarlson https://github.com/SiftScience/sift-ruby/pull/49 fixes the typo on the README.md
