### ISSUE TITLE
Update to use v205

### ISSUE THREAD

**Issue by Shamash2014** [SiftScience/sift-ruby#60]
Since latest version available, should we actually use it? 

<img width="1420" alt="screen shot 2018-07-02 at 11 03 27 am" src="https://user-images.githubusercontent.com/8573566/42152037-a52d9872-7de7-11e8-8b62-c4063578ff65.png">

**Comment by Shamash2014** [comment]
Thanks for the fast response! It's clear. Can we actually improve the docs so when code samples got used, we use latest API version? Example:

Right now ruby gem is fixed for API version v204. Docs point out automatically to v205. Just updating code sample to `gem 'sift', '~> 3.0.0'` should do the trick. 

Can you point me in the right direction? I'll do the pull request :)

**Comment by quanpod** [comment]
Thanks @Shamash2014 - I'll file something to fix that (unfortunately our docs are in a private repo), appreciate the willingness to contribute!

**Comment by aniranjan-sift** [comment]
Closing as it's older than 2019

**Comment by Mstafamhamadmhamad** [comment]
> Since latest version available, should we actually use it? 
> 
> <img width="1420" alt="screen shot 2018-07-02 at 11 03 27 am" src="https://user-images.githubusercontent.com/8573566/42152037-a52d9872-7de7-11e8-8b62-c4063578ff65.png">
> 

img width="1420" alt="screen shot 2018-07-02 at 11 03 27 am" src="https://user-images.githubusercontent.com/8573566/42152037-a52d9872-7de7-11e8-8b62-c4063578ff65.png

**Comment by Mstafamhamadmhamad** [comment]
[]()

**Comment by Mstafamhamadmhamad** [comment]
> The current version of the Ruby SDK defaults to `v205`, but you can force it to use an older version of the API.
> 
> As for actually using `v205`, there were [breaking changes](https://github.com/SiftScience/sift-ruby/blob/463d7edc867b6489fc4dea366d50a3d4f49a8f2f/HISTORY#L7-L16), so it depends. If you're using `$create_content`, `$update_content`, `$send_message`, or `$submit_review`,  you need to change the data you're sending when you upgrade. For all other events, validation is stricter. You can get an idea if you'd have any validation failures by looking for warnings in [Api Logs](https://console.siftscience.com/developer/api-logs?) in the developer console. You can also try sending events to your sandbox account using `v205` before making production changes.
