### ISSUE TITLE
Swallowing exceptions

### ISSUE THREAD

**Issue by exAspArk** [SiftScience/sift-ruby#66]
Hi,

Is it possible to update the client, so it doesn't silently swallow the exceptions? 

https://github.com/SiftScience/sift-ruby/blob/62809039562b037fa424916ccded20e174960ef8/lib/sift/client.rb#L231-L238

Instead of receiving a `Response` object I'm receiving some random `nil` values sometimes. 

For example, instead of using a logger, I'd like to report the errors to my error tracking app.

**Comment by ehrmann** [comment]
I agree with not swallowing exceptions; it hides what's going on. It looks like Sift errors (or anything(?) with a valid HTTP response) result in a `Response`, but things like `SocketErrors` get swallowed.

I'm leaning towards just removing the `rescue` and letting clients handle the exception and logging. This would have to be a major version bump to not break existing integrations.

**Comment by alexcameron89** [comment]
I don't know if raising the error for user's to handle is the right approach, but I would love to see at least an unsuccessful response from the gem in that case rather than `nil`. I've wondered why I sometimes receive a `nil` response, and I don't think it serves well as a way of dealing with unknown errors.

**Comment by exAspArk** [comment]
Yes, unfortunately, it'll introduce a breaking change. But in my opinion, removing `rescue` is a better solution in the long run. Which gives users the ability to handle the errors as they want 👍

In my particular case, I'm seeing `Net::ReadTimeout` exceptions being swallowed. To address the timeout exceptions, I implemented a retry functionality. But still, it doesn't help in 100% cases. Does Sift have some stats on how long API requests take: median response time, 90th percentile or something like that?

As far as I understand, it is possible to set a `timeout` option which will be set as a `read_timeout` through `HTTParty`. But I would like to avoid increasing the default 2 seconds timeout with 3 retries.

**Comment by ehrmann** [comment]
>  would love to see at least an unsuccessful response

@alexcameron89 In these cases, there isn't a response. I was playing with httparty (the client we use), made a request to `http://domain.invalid`, and got a `SocketError` because the address couldn't resolve. There isn't anything more than an exception (or `nil`) to hand back.

**Comment by ehrmann** [comment]
@exAspArk  I'm fine with the breaking change. There's already another much smaller one in the pipe. We just have to do a major version bump and communicate it clearly.

We post the median score latency at https://status.sift.com/. Asynchronous event latencies are significant faster. We host in Northern Virginia, so be sure to add ping times to that. You can get more detailed stats from our support team.

You can pass a different timeout to `Sift::Client.new()` (and httparty has some hooks), but I agree with not raising it much above 2s.

**Comment by garylee1** [comment]
@exAspArk – this has been fixed and released with v4.0.0!
